In [1]:
import numpy as np
from my_solvers.solvers.Solver_SD_LS import Solver_SD_LS

sol = Solver_SD_LS( max_iter = 1e3 , tol = 1e-8 )

A = np.array([[1, 3, -2], [1, 2, 5], [-4, 3, 1]])
b = np.array([[8],[10],[5]])
X0 = np.array([[0.5],[3],[0.1]])


X_ls = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "lin_search" )
X_cg = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "conj_grad" )
X_bt = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "back_track_iter" , beta = 0.8 )

print(X_ls,)
print(X_cg,)
print(X_bt,)
print(A.dot(X_ls)-b)
print(A.dot(X_cg)-b)
print(A.dot(X_bt)-b)




[[1.01014126]
 [2.78563384]
 [0.68367116]]
[[1.01021475]
 [2.78572486]
 [0.68365412]]
[[1.01020408]
 [2.78571429]
 [0.68367347]]
[[-2.99560526e-04]
 [-2.35244357e-04]
 [ 7.64274037e-06]]
[[ 8.10943379e-05]
 [-6.49264682e-05]
 [-3.02948789e-05]]
[[-8.75889583e-10]
 [ 2.40208031e-08]
 [ 1.78027104e-08]]
