In [1]:
import numpy as np
from my_solvers.solvers.Solver_SD_LS import Solver_SD_LS

sol = Solver_SD_LS( max_iter = 1e3 , tol = 1e-8 )

A = np.array([[1, 3, -2], [1, 2, 5], [-4, 3, 1]])
b = np.array([[8],[10],[5]])
X0 = np.array([[0.5],[3],[0.1]])


X_ls = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "lin_search" )
X_cg = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "conj_grad" )

print(np.round(X_ls,3))
print(np.round(X_cg,3))
print(A.dot(X_ls)-b)
print(A.dot(X_cg)-b)




[[1.01 ]
 [2.786]
 [0.684]]
[[0.988]
 [2.792]
 [0.667]]
[[-2.99560526e-04]
 [-2.35244357e-04]
 [ 7.64274037e-06]]
[[ 0.03169469]
 [-0.09376253]
 [ 0.09121923]]
