In [1]:
import numpy as np
from my_solvers.solvers.Solver_SD_LS import Solver_SD_LS

sol = Solver_SD_LS( max_iter = 1e3 , tol = 1e-8 )

A = np.array([[1, 3, -2], [1, 2, 5], [-4, 3, 1]])
b = np.array([[8],[10],[5]])
X0 = np.array([[0.5],[3],[0.1]])


X_ls = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "lin_search" )
X_cg = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "conj_grad" )
X_bt = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "back_track_iter" , BT_factor = 0.5 )
X_bbs = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "barzilai_borwein_short" )
X_bbl = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "barzilai_borwein_long" )
X_bba = sol.solve( (A.T).dot(A) , (A.T).dot(b) , X0 , method = "barzilai_borwein_alt" )

# print(X_ls)
# print(X_cg)
# print(X_bt)
# print(X_bb)
print(A.dot(X_ls)-b)
print(A.dot(X_cg)-b)
print(A.dot(X_bt)-b)
print(A.dot(X_bbs)-b)
print(A.dot(X_bbl)-b)
print(A.dot(X_bba)-b)




[[-2.99560526e-04]
 [-2.35244357e-04]
 [ 7.64274037e-06]]
[[0.0000000e+00]
 [0.0000000e+00]
 [8.8817842e-16]]
[[-6.20992300e-06]
 [ 1.89400148e-04]
 [ 1.40155618e-04]]
[[-4.91482131e-06]
 [ 1.07072490e-04]
 [ 7.99528230e-05]]
[[-4.46405778e-05]
 [-1.55528367e-05]
 [ 1.51735316e-05]]
[[-1.13237173e-05]
 [ 1.41153282e-04]
 [ 1.08261499e-04]]
